name: flutter_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  paixs_utils:
    path: package/paixs_utils
  provider: ^5.0.0
  readmore: ^1.0.1
  flutter_slidable: ^0.5.7
  package_info: 0.4.1
  open_file: ^3.0.3
  progress_dialog: 1.2.0
  permission_handler: ^7.1.0  #权限
  path_provider: 2.0.1
  loading_indicator: ^1.2.0
  flutter_styled_toast:
  # 轮播图
  flutter_swiper: ^1.1.4
  rive: ^0.6.8
  shared_preferences: ^2.0.3
  flutter_xlider: ^3.4.0
  wave: ^0.2.0
  flutter_staggered_grid_view: ^0.4.0
  lazy_data_table: ^0.2.1
  waterfall_flow: 3.0.1
  flutter_datetime_picker: 1.5.0

  # 视频播放
#  fijkplayer: 0.8.7

  # 融云对接
  flutter_rong:
    path: package/imkit-flutter-quickstart
  
  # 加密包，如sha1
  crypto: ^3.0.1
  
  # 系统信息
  system_info: ^1.0.0


  image_picker: 0.7.4

  # 设备信息
  device_info: 2.0.1


  # 显示二维码
  qr_flutter: 4.0.0

  # 剪贴板
  clipboard: 0.1.3

  # 保存图片
  image_gallery_saver: 1.6.9

  # 360全景
  panorama: ^0.4.1


  # 微博登录
  weibo_kit:
    git:
      url: https://github.com/rxreader/weibo_kit.git


  animated_digit: ^2.0.2


  
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - package/paixs_utils/assets/svg/
    - package/imkit-flutter-quickstart/assets/RCFlutterConf.json
    - package/imkit-flutter-quickstart/assets/combine.json
    - package/imkit-flutter-quickstart/assets/
    - assets/img/
    - assets/img/dibu/
    - assets/svg/
    - assets/riv/
    - data/province.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
